name: Run tests manual with allure report

on:
  workflow_dispatch: 

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -t saucedemo_ci . 
      
    - name: Run the Docker container
      run: docker run saucedemo_ci

  allure-report:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      with:
        allure-results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-results/history
        keep_reports: 20
        alluredoc_repo: ${{ github.repository }}
        gh_token: ${{ secrets.ALLURE_REPORT_TOKEN }}

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ALLURE_REPORT_TOKEN }}
        publish_dir: allure-results
        publish_branch: gh-pages