name: Run tests manual 

on:
  workflow_dispatch: 

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -t saucedemo_ci . 
      
    - name: Run the Docker container
      run: docker run saucedemo_ci