name: Run tests manual with install allure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t saucedemo_ci .

      - name: Run the Docker container
        run: docker run saucedemo_ci

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Generate Allure Results
        run: allure generate --clean -o allure-results

      - name: Archive Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

  allure-report:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
          sudo tar -zxvf allure-2.23.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download Allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results

      - name: Generate Allure Report
        run: |
          allure generate -c allure-results -o allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ALLURE_REPORT_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
